/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ThingsToDoRouteImport } from './routes/things-to-do'
import { Route as SuitesSlugRouteImport } from './routes/suites.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingsToDoRoute = ThingsToDoRouteImport.update({
  id: '/things-to-do',
  path: '/things-to-do',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesSlugRoute = SuitesSlugRouteImport.update({
  id: '/suites/$slug',
  path: '/suites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/things-to-do': typeof ThingsToDoRoute
  '/suites/$slug': typeof SuitesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/things-to-do': typeof ThingsToDoRoute
  '/suites/$slug': typeof SuitesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/things-to-do': typeof ThingsToDoRoute
  '/suites/$slug': typeof SuitesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/things-to-do' | '/suites/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/things-to-do' | '/suites/$slug'
  id: '__root__' | '/' | '/about' | '/things-to-do' | '/suites/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ThingsToDoRoute: typeof ThingsToDoRoute
  SuitesSlugRoute: typeof SuitesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/things-to-do': {
      id: '/things-to-do'
      path: '/things-to-do'
      fullPath: '/things-to-do'
      preLoaderRoute: typeof ThingsToDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/$slug': {
      id: '/suites/$slug'
      path: '/suites/$slug'
      fullPath: '/suites/$slug'
      preLoaderRoute: typeof SuitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ThingsToDoRoute: ThingsToDoRoute,
  SuitesSlugRoute: SuitesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
